language: rust
rust:
  - nightly
  - stable
  - 1.20.0

os:
  - linux
  - osx

script:
  - cargo test
  - cargo test --features=unsafe --release
  - cargo test --features=no-stdlib
  - cargo test --release

